name: Deployment pipeline

on:
  push: # when pushing or merging (the name of the event is also 'push' when merging a pull request)
    branches:
      - master # ^ to the master branch
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          # wait for the server to start: https://github.com/cypress-io/github-action
          wait-on: http://localhost:5000
      # Deploy to Heroku action: https://github.com/marketplace/actions/deploy-to-heroku
      - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}} # run conditionally only when a pull request is merged (in this case, push meand pull request merge). https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
        with:
          # the secret has been generated by the Heroku CLI and has been set in our Github repository's settings.
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ndeamador-fso2020-pokedex" #Must be unique in Heroku
          heroku_email: "ndeamador@gmail.com"
          # adding healthcheck, to make sure the application is running after depoloyment:
          healthcheck: "https://ndeamador-fso2020-pokedex.herokuapp.com/health" # visit url (GET request) to check that the app is running after deployment
          checkstring: "ok" # look for othis specific string in the page above
          delay: 5 # a delay (in seconds) to prevent that the healtcheck is performed before the application has been set up on Heroku.
          rollbackonhealthcheckfailed: true # rollback to previous (working) version if healthcheck fails.
      # third party notification action (action-slack: https://github.com/marketplace/actions/action-slack)
      - uses: 8398a7/action-slack@v3
        if: success()
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message). Check https://action-slack.netlify.app/fields
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                title: 'Successful Heroku Deployment',
                text: `A new version deployed to https://ndeamador-fso2020-pokedex.herokuapp.com/ (${process.env.AS_JOB}) by${process.env.AS_AUTHOR}\nBuild took ${process.env.AS_TOOK}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      # failure notification (not custom):


      # - uses: 8398a7/action-slack@v3
      #   if: failure() || cancelled()
      #   with:
      #     status: ${{ job.status }}
      #     author_name: ${{process.env.AS_JOB}}
      #     fields: repo,message,commit,author,took # selectable (default: repo,message). Check https://action-slack.netlify.app/fields
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

  versioning:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # The following step increases the version when a pull request is merged and tag the release with a version number.
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598 # the string after the @ is the version hash in the third party library, specified in order to prevent issues in case the contents of the numbered version are changed. https://fullstackopen.com/en/part11/keeping_green#a-note-about-using-third-party-actions
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
        env:
          # because github-tag-action is third party, we need to provide the token for authentication in the repository.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  Logs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: console messages
        run: |
          echo 'condition: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}'
          echo 'title contains #skip:  ${{ contains(github.event.head_commit.message, '#skip')}}'
          echo "head_commit: ${{github.event.head_commit.message}}"
          echo "github.base_ref: ${{github.base_ref}}"
          echo "github.head_ref: ${{github.head_ref}}"
          echo "github.event_name: ${{github.event_name}}"
          echo "title contains ${{contains(github.event.head_commit.message, 'contain_test')}}"
          echo "title doesn't ${{contains(github.event.head_commit.message, 'nothing')}}"
          echo "event url: ${{github.event.url}}"
          echo "event id: ${{github.event.id}}"
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
